### ISSUE TITLE
error on authenticate

### ISSUE THREAD

**Issue by carlsunderman** [maxi07/Teams-Presence#6]
I keep getting 
Failed to authenticate. 'access_token'
Failed authorizing, empty token (1/10). Will try again in 10 seconds.
Starting authentication workflow.

also, the appi id from the original page no longer works as well.

any ideas?

**Comment by maxi07** [comment]
Hey @carlsunderman,
Thanks for checking out my script!
Have you tried setting up your own Azure AD app? 

You can find some instructions in the [wiki](https://github.com/maxi07/Teams-Presence/wiki/Azure-AD-App).

**Comment by carlsunderman** [comment]
yeah, after i posted the issue i'm having, i think may have figured it out. i enabled public client flows, which seemed to resolve my issue. Thank you for such a quick response!!! i'm really intrigued by your script and thank you very much.

**Comment by carlsunderman** [comment]
I am getting an empty json response now, any ideas?

Fetching new data
JSON result is empty! Will try again.

**Comment by carlsunderman** [comment]
@maxi07 whenever i try to run it now i get

  File "teams-presence.py", line 182
    print("Time until next run: " + timer, end="\r")
                                              ^
SyntaxError: invalid syntax

when i comment out those lines, same error at/around line 401

**Comment by maxi07** [comment]
I have setup a new virtual environment and tried resproducing your issue. In my case everything seems to be working fine. 
Maybe there is an issue with wrong packages on your side, I would suggest you try using a virtual environment as well and check your package versions. Also, are you using the latest python3?

Try the following ([source](https://geektechstuff.com/2019/01/14/creating-a-virtual-python-environment-python/)):

- Open Terminal / BASH
- Create a folder for your project `mkdir folder_name`
- Navigate to the project folder `cd folder_name`
- Create the virtual environment `python3 -m venv ./venv`
- Activate the virtual environment `source ./venv/bin/activate`
- Clone the project again and check if the error still occurs.

![image](https://user-images.githubusercontent.com/7480270/101154245-c2833280-3625-11eb-87f3-dc0ac3c188b4.png)

**Comment by maxi07** [comment]
> yeah, after i posted the issue i'm having, i think may have figured it out. i enabled public client flows, which seemed to resolve my issue. Thank you for such a quick response!!! i'm really intrigued by your script and thank you very much.

I have added a note in the wiki, thanks for notifying me!

**Comment by carlsunderman** [comment]
just fyi, gpiozero and msal are not installed with your setup.sh

**Comment by carlsunderman** [comment]
# #
![Untitled](https://user-images.githubusercontent.com/3720237/101212177-e81c3600-363d-11eb-9011-5e81750faf14.jpg)

I keep getting empty responses

**Comment by carlsunderman** [comment]
So the issue ended up being not have Presence,Read enabled in the scope on azure. For anyone else who may be interested

**Comment by maxi07** [comment]
Awesome, good to know that you have resolved the issue.
I will add a note into the FAQ in the wiki.
