### ISSUE TITLE
Add support for Unicorn HAT Mini

### ISSUE THREAD

**Issue by NiceLucius** [maxi07/Teams-Presence#7]
The Unicorn pHAT is not produced anymore. The successor is the Unicorn HAT mini. Could support be added?

**Comment by maxi07** [comment]
Hey @NiceLucius, thanks for reaching out. I have heard about the issue and I am planning to integrate the Unicorn HAT mini into the script, hopefully with auto detection. But this will take some time. If you have any suggestions feel free to start a pull request.

Max

**Comment by NiceLucius** [comment]
Hi @maxi07. I've started on the support for blinkt but had another major issue. I couldn't retrieve the presence information. After a very long search I discovered that the SCOPES array includes correctly "User.Read" but misses "Presence.Read". Instead, the array includes a "User.ReadBasic.All" which you don't need. Please correct this. You can then also make use of the fact that the graph presence API is not beta anymore so you can use the URL which includes "v1.0". Thanks.

**Comment by maxi07** [comment]
Hey @NiceLucius , I made some changes to the code and followed your suggestion. Thank you for noticing!

**Comment by maxi07** [comment]
As there does not seem to be any demand for this feature, this will be closed with **wontfix**. Feel free to submit a pull request!
