### ISSUE TITLE
2FA option 

### ISSUE THREAD

**Issue by JayBabs** [maxi07/Teams-Presence#8]
I was wondering if this is possible to add the 2FA authentification ? I would like to use the application but my account is protected with Duo Mobile. Feel free to pm me on Discord at thebabeu#1709

**Comment by maxi07** [comment]
Hey there, my Microsoft Account is protected with 2FA, but the [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-python) platform handles the authentication just fine with **Azure AD**.

**Comment by maxi07** [comment]
As there is no further feedback, I will close the issue.
