### ISSUE TITLE
Failed to authenticate. module 'msal' has no attribute 'SerializableTokenCache'

### ISSUE THREAD

**Issue by JayBabs** [maxi07/Teams-Presence#9]
It's works on my RPi 4 B but not on my RPi W. 
I got the same version of the module but i can't seems to find the solution

**Comment by maxi07** [comment]
Hey @JayBabs! Thanks for reaching out. Did you make sure, that you have installed all libraries? Please run install.sh with sudo first. 
What is the exact issue you are experiencing?

**Comment by maxi07** [comment]
As there is no further feedback, I will close the issue.
